### ISSUE TITLE
Incomplete documentation for WebRenderer.createRef()

### ISSUE THREAD

**Issue by AvneeshSarwate** [elemaudio/elementary#51] opened 2024-06-28 19:54 UTC
The documentation for `createRef()` does not show how/why/when to use the third parameter (children), neither in the [guide](https://www.elementary.audio/docs/guides/Using_Refs) nor the [api doc](https://www.elementary.audio/docs/packages/web-renderer#createref)

**Comment by nick-thompson** [comment] 2024-06-29 14:23
Hey @AvneeshSarwate good catch, thanks for letting me know! There is this one line in the guide

```
let [svf, setFilterProps] = createNode("svf", {mode: 'lowpass'}, [filterInput]);
```

which I think was intended to demonstrate a case for using that children parameter, but it's quite buried. I'll update that api doc to be more clear

**Comment by nick-thompson** [comment] 2024-07-03 14:52
I've just pushed a change to the website! Closing here, please reopen if the change feels insufficient. Thank you

**Closed by nick-thompson** 2024-07-03 14:52 UTC

**Comment by AvneeshSarwate** [comment] 2024-07-03 14:58
excellent, appreciate the quick turnaround!
